### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Centros** [UpcraftLP/WorldLimiterMod#3]
So i'm not quite sure why but I have a theory how this might of happened. Anywho the scenario is I left everything default after I installed this mod. I started out on a brand new map and I have a private server up for me and my friends run through the twitch curse client. The server has been active for about a month or so with no problems. Today I wanted to go out and find a snow biome to find some blizz from TE and I took my Viescraft aircraft to fly around in. After quite a bit of flying I didn't even see the message that I was getting close to the border but randomly the server crashed. It auto restarted and when I rejoined it crashed again before I even got fully loaded. After checking the crash report it was saying this

PM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.entity.Entity.func_70016_h(DDD)V
	at mod.upcraftlp.worldlimiter.WorldBorderEvents.teleportEntities(WorldBorderEvents.java:118)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_46_WorldBorderEvents_teleportEntities_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:531)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2005)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

The first few lines about the world boarder is why I figured this was a problem with this mod.

I changed this line in the config 
defines how many blocks a player can travel before being teleported, set to 0 to disable [range: 0 ~ 2147483647, default: 10000]
    I:radius=10

After that I was able to get back in and I was standing on my aircraft. I got black in and tried to go in the direction I was heading and it crashed again only now every time the server restarts it auto crashes.

I have not attempted anything else at this point so idk if it can be recreated in a fresh install but my theory is it dont like veiscraft airships.
[crash-2017-10-27_21.09.11-server.txt](https://github.com/UpcraftLP/WorldLimiterMod/files/1423811/crash-2017-10-27_21.09.11-server.txt)

**Comment by UpcraftLP** [comment]
viescraft airships were ignored by my mod because they're no living entities, will be fixed in v1.2.0.
I'll publish a release later today or tomorrow.
